# .appveyor.yml
#
# AppVeyor configuration to test Net::SSLeay on Windows
#
# Various parts collected from:
# cache, install and build_script sections thanks to blogs.perl.org
# entries by eserte and mauke.
#
# Using $Config{make} for not needing to know if make is called dmake,
# gmake, etc. from a PerlMonks posting by pyrt.

# 2017 is Server 2016, earlier are Server 2012R2
image:
  - Visual Studio 2017
  - Visual Studio 2015

# There's also Any CPU. Note: this does not select 32bit or 64bit
# OS. Both server versions are 64bit and this seems to be related to
# Visual Studio configuration. We use this to choose either 64bit or
# 32bit Strawberry Perl.
platform:
  - x64
  - x86

# Environment variables need to:
# - use defaults for external tests and other Makefile.PL prompts
# - make sure that we use OpenSSL from Strawberry Perl instead of, for
#   example, c:\OpenSSL-Win32 that comes pre-installed on the VM.
environment:
  AUTOMATED_TESTING: 1
  PERL_MM_USE_DEFAULT: 1
  RELEASE_TESTING: 0
  OPENSSL_PREFIX: C:\strawberry\c
  matrix:
    - perl: 5.26.2.1
#    - perl: 5.24.4.1
#    - perl: 5.22.3.1
#    - perl: 5.20.3.3
#    - perl: 5.18.4.1
#    - perl: 5.16.3.20170202
#    - perl: 5.14.4.1
    # For 5.12.3.1 choco is directed to strawberry-perl.googlecode.com
    # which no longer exists
    # - perl: 5.12.3.1

# If branch name hints that it's for Travis CI, skip build
branches:
  except:
    - /travis/

# Tags need not to trigger builds
skip_tags: true

# Speed up things: just get this specific gommit, not entire repo
shallow_clone: true

cache:
  - C:\strawberry

install:
  - echo Using perl %perl% on %APPVEYOR_BUILD_WORKER_IMAGE% %PLATFORM%
  - if /I "%PLATFORM%" == "x86" (set x86=--force86) else (set x86="")
  - echo if not exist "C:\strawberry" choco install strawberryperl --yes %x86% --version %perl%
  - if not exist "C:\strawberry" choco install strawberryperl --yes %x86% --version %perl%
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - cpanm --quiet --installdeps --with-develop --notest .
  - perl -V

build_script:
  - perl Makefile.PL
  - perl -MConfig -e "system $Config{make}"

test_script:
  - perl -MConfig -e "system $Config{make}, 'test'"
